version: "3.7"

services:

  t2:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: "America/New_York"
      T2_SERVERNAME: "Docker Loki Test"
      T2_MAX_PLAYERS: 64
      T2_DEFAULT_MISSIONTYPE: "Lakrabbit"
      T2_DEFAULT_MAP: "VaubanLak"
      T2_PUGPW_ALWAYSON: 0
      T2_PUG_PASSWORD: "pickup"
      T2_PUGAUTOPW_TOURNY: 1
      T2_TimeLimit: 45
      T2_Telnet: 1
      T2_Telnet_Port: 55555
      T2_BaseRapeMin: 14
      T2_TurretMin: 10
      T2_AntiPackMin: 6
      T2_ObserverTimeout: 1200
      T2_BanTime: 1800
      T2_EmptyServerReset: 1
      T2_EmptyServerResetTime: 120
      T2_PacketRate: 32
      T2_PacketSize: 450
      T2_NoSmurfs: 0
      T2_ADMIN_LIST: ""
      T2_SA_LIST: ""
      T2_VoteAdmin: 0
      T2_Admin2AdminOthers: 0
      T2_JoinBanner: "<color:3cb4b4><font:Sui Generis:22>Docker Loki Test\\n<color:3cb4b4><font:Univers:16>Server Hosted by Someone\\n<color:3cb4b4><font:Univers:16>Get Mappacks at https://playt2.com/"
      T2_JoinBannerLines: 3
      T2_JoinBannerTime: 6
      T2_LoadScreenColor1: "05edad"
      T2_LoadScreenColor2: "29DEE7"
      T2_LoadScreenColor3: "33CCCC"
      T2_LoadScreenLine1: "Join Discord:"
      T2_LoadScreenLine1_Msg: "<a:playt2.com/discord>playt2.com/discord</a>"
      T2_LoadScreenLine2: "Game Modes:"
      T2_LoadScreenLine2_Msg: "LakRabbit, Capture the Flag, DeathMatch, (Light Only) Capture the Flag"
      T2_LoadScreenLine3: "Get Mappacks:"
      T2_LoadScreenLine3_Msg: "<a:playt2.com/mappacks>playt2.com/mappacks</a>"
      T2_LoadScreenLine4: "Server Location:"
      T2_LoadScreenLine4_Msg: "Somewhere"
      T2_LoadScreenLine5: "Server Infrastructure GitHub:"
      T2_LoadScreenLine5_Msg: "https://github.com/amineo/docker-tribesnext-server"
      T2_LoadScreenLine6: "TacoServer GitHub:"
      T2_LoadScreenLine6_Msg: "https://github.com/ChocoTaco1/TacoServer"
      T2_LoadScreenMOTD1: "Have fun!"
      T2_LoadScreenMOTD2: "This is a Loki Linux Server!"
      T2_LoadScreenMOTD3: " "
      T2_LoadScreenMOTD4: " "
    secrets:
      - t2.admin.password
      - t2.classic.superadmin.password
      - t2.classic.telnet.password
      - t2.classic.telnet.listen.password

    ports:
      - target: 28000
        published: 28000
        protocol: udp
        mode: host
      - target: 55555
        protocol: tcp
        published: 666
        mode: host

    volumes:
      - serverStats:/home/gameserv/.loki/tribes2/Classic/serverStats
      - stats:/home/gameserv/.loki/tribes2/Classic/stats
      - logs:/home/gameserv/.loki/tribes2/Classic/logs
      - gamedata:/home/gameserv/.loki/tribes2/

    networks:
      - t2-net

    healthcheck:
      test: ["CMD-SHELL", "nc -z -u 127.0.0.1 28000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure

    logging:
      options:
        max-size: "10m"

volumes:
  serverStats:
  stats:
  logs:
  gamedata:

networks:
  t2-net:
    driver: overlay

secrets:
  t2.admin.password:
    external: true
    name: t2.admin.password.v1
  t2.classic.superadmin.password:
    external: true
    name: t2.classic.superadmin.password.v1
  t2.classic.telnet.password:
    external: true
    name: t2.classic.telnet.password.v1
  t2.classic.telnet.listen.password:
    external: true
    name: t2.classic.telnet.listen.password.v1